### PR TITLE
Make React-Native-Draggable Great Again (and modern!)

### PR DESCRIPTION
**Pull request by baconcheese113**
Wanted to use your Draggable component in my own stuff today and noticed I was rewriting most of your functionality to create my own. 

Since this is the most popular package for React Native draggables I figured I'll just submit a PR with my changes. I refactored Draggable.js to a functional component (along with some other cleaning) and created a brand new example project with `react-native init`

Only thing not working yet is draggables staying where they're released (instead of snapping back to their start position)

******DO NOT MERGE YET*******

### CODE REVIEW

**Comment by baconcheese113** [comment]
This will also resolve #26

**Comment by tongyy** [comment]
@baconcheese113 are you willing to be a collaborator and contribute to this project? Since I am not available to maintain this for some reason, I would like to invite more people to continue with it.

**Comment by baconcheese113** [comment]
Yea, I'd gladly take over as much as you're comfortable with

**Comment by tongyy** [comment]
great! Now you can manage and push into the master of this repo. I will keep updating NPM repo and your version will start from 2.0.0

**Comment by baconcheese113** [comment]
Sweet, I just started with this repo yesterday and don't currently have a way to test on iOS. Can you help me check to make sure all the functionality is still working correctly? The Draggable component should be stable at this point.

**Comment by tongyy** [comment]
There is one of the reasons why I can't maintain this repo myself. for now, I don't even have the environment to test and code on it. anyway, I will try to get a mac and test it before I publish it into NPM.

**Comment by baconcheese113** [comment]
Oh I can check with my mac from work then, still could use your help making sure the functionality behaves like you had it before on android

**Comment by tongyy** [comment]
well done! I just got my environment back. I've tested both IOS and Android.
 It works very well.

**Comment by tongyy** [comment]
Are you ready to merge the code? I would update these two lines as follows to fix #31 (only happens when devices are Android )
[Ref:touchableopacity-with-parent-panresponder](https://stackoverflow.com/questions/47568850/touchableopacity-with-parent-panresponder/50576784#50576784)
```
      onMoveShouldSetPanResponder: (evt, gestureState) => !(gestureState.dx === 0 && gestureState.dy === 0),
      onMoveShouldSetPanResponderCapture: (evt, gestureState) => false,
```

**Comment by baconcheese113** [comment]
Was considering adding 
```
      onMoveShouldSetPanResponder: (_, gestureState) => {
        const {dx, dy} = gestureState;
        return dx > 2 || dx < -2 || dy > 2 || dy < -2;
      },

      onMoveShouldSetPanResponderCapture: (_, gestureState) => {
        const {dx, dy} = gestureState;
        return dx > 2 || dx < -2 || dy > 2 || dy < -2;
      },
```
But i'm unable to reproduce the bug from #31 at all. Can you?

**Comment by tongyy** [comment]
yep you can only reproduce it on an Android device instead of a simulator. I can reproduce it on my Asus Z00AD with Android 5.0 version OS.
I agree with you for the better UX we can set dx and dy to 2. by the way I changed the code a little bit. 
I tested, and it's good to go. what do you think?
    ```
let isDragging = (gestureState) => Math.abs(gestureState.dx) > 2 || Math.abs(gestureState.dy) > 2;
    return PanResponder.create({
      onMoveShouldSetPanResponder: (_, gestureState) => isDragging(gestureState),
      onMoveShouldSetPanResponderCapture: (_, gestureState) => isDragging(gestureState),
..
```

**Comment by baconcheese113** [comment]
Couple questions:
1) What do you think about making `reverse` default to false? Not sure what the use cases are, but all the times I'd want to use this it'd be false.
2) Cool if I add support for "constraints" to allow panning only inside a specified area?

**Comment by tongyy** [comment]
for 1, there was a funny story behind it. you can see [the demo picture](https://raw.githubusercontent.com/tongyy/react-native-draggable/master/demo/demo2.png) it's draggable and also should be that place after dragging. I just saw some cases they are using it as True [CardGame](https://github.com/MAudeon/CardGame/blob/master/App/Components/GameView/Card.js)
However, I also saw some projects using it as False. That's would be your call. 

for2, why not? it will be a new feature.

**Comment by baconcheese113** [comment]
:/ It's not ready yet

**Comment by tongyy** [comment]
Sorry about it. I saw you had many commits for this PR, but it's okay.  I have tested on both simulators and devices. you can either open a pull request or commit directly. I will test again before publishing it into NPM.

**Pull request merged**
