### PR TITLE
Version 3: Robust child support, constraints, naming conventions, performance boost, customization, z-ordering correctly

### PR DESCRIPTION
**Pull request by baconcheese113**
### ********* I WILL MERGE IF ACCEPTED ***********

So these are the rest of the changes I planned on making. Lots of breaking changes, so it'll require another major version bump (assuming we're following semver).

Some of the big things are:
**Children** - Children can be passed in and no longer will have the default styling applied. Also their bounds are calculated correctly regardless of number of nested components.

**Constraints** - min and max x/y can now be passed in and will constrain the draggable based on it's bounds. This works fine for children as well. Only issue I've seen is with the bottom navigation bar on android not being accounted for correctly by Dimensions.height

**Naming Conventions** - all functions start with `on` and booleans are questions. This will break a bunch of stuff but will be better moving forward imo. Also the `drag` callbacks have all been renamed to better reflect what they do.

**Performance Boost** - fixed several places with unnecessary computation, so should be smoother.

**Customization** - I removed `renderShape` along with the removal of several other props, and instead allow all basic shape customizing to be aggregated together. 

**Z-ordering** - the z-index/elevation we were using before was causing a lot of inconsistencies between where things were haptically and visually. I've now set the default z-index to be `1` and instead the user should reorder their props to set what is above or below. Then they can also pass in a `z` from there to make sure the visual display order lines up

### ********* I WILL MERGE IF ACCEPTED ***********

### CODE REVIEW

**Comment by baconcheese113** [comment]
Also, noticed you changed the formatting last time. Was that from you running `npm run lint`? It'd be good to get on the same page there

**Comment by tongyy** [comment]
@baconcheese113 yep I ran `npm run lint`.

**Comment by baconcheese113** [comment]
Hmmm, if you run it on my code now does it still change stuff?

**Comment by tongyy** [comment]
nothing change. it's correct

**Comment by baconcheese113** [comment]
Last things I want to add are:

1. `onRelease` function that will be called only on the final release of the press
2. `debug` bool that will show the area a draggable is constrained to. Any other ideas for what to show with that?
3. `TouchableOpacityProps` and `AnimatedViewProps` allowing the user to pass through any props that we don't support

**Comment by baconcheese113** [comment]
@tongyy Alright, I think v3 is ready!! 🎉 🎉 Can you think of anything else you'd want from that debug prop?

Also can you test iOS?

**Comment by baconcheese113** [comment]
On iOS now and noticing an issue selecting draggables with custom children

**Comment by baconcheese113** [comment]
image
This is with `style={{bottom: 20, right: 10}}`
`SafeAreaView` doesn't support keeping things out of the navigation bar on android....so my vote is to just keep android and iOS behaving as similar as possible

**Comment by baconcheese113** [comment]
image
This is the alternative that we'd _**want**_ to use (green is the padding from `SafeAreaView`).
Here you can see `style={{bottom: 0, right: 10}}` is completed hidden on android because `SafeAreaView` doesn't address the nav bar

**Comment by tongyy** [comment]
[The purpose of SafeAreaView is to render content within the safe area boundaries of a device. It is currently **only applicable to iOS devices with iOS version 11 or later.**
](https://facebook.github.io/react-native/docs/safeareaview)

yep keeping android and iOS behaving as similar as possible is a good idea. We can't handle all cases because there are too many devices and os versions. Developers should handle this depends on what they are targeting.

**Comment by baconcheese113** [comment]
Well that solution I came up with probably won't work because having a parent `SafeAreaView` seems to invalidate any child `SafeAreaViews`

This is the approach I was hoping would work:
```
  return (
    <>
      <View style={{width, height, position: 'absolute'}}>
        <SafeAreaView style={{backgroundColor: 'green'}} />
          <View style={{backgroundColor: 'red', flex: 1}}>
            <View style={{ backgroundColor: 'blue', position: 'absolute', bottom: 20, right: 10}}>
              <Text>Position Me</Text>
            </View>
          </View>
      </View>
      <SafeAreaView>
        <Text>Inside the normal flow</Text>
      </SafeAreaView>
    </>
  )
```
However if you change those fragments to `SafeAreaView` then the `SafeAreaView` child of the absolute positioned `View` doesn't work....

That being said, my vote is to release v3 as is and maybe revisit in the future to patch, does that work for you?

**Comment by tongyy** [comment]
I just tested the latest example on IOS. When I was dragging Custom Component, Constrained Slider was dragging at the same time. Android doesn't have this behavior.

**Comment by baconcheese113** [comment]
Yea, working on that currently

**Comment by baconcheese113** [comment]
Oh also can you add me as a collaborator for NPM? I'll still let you handle all of that, just would appreciate the exposure.

**Comment by tongyy** [comment]
Sure! can you give me your NPM account? I am going to invite you

**Comment by baconcheese113** [comment]
baconcheese113
<baconcheese113@hotmail.com>

**Comment by baconcheese113** [comment]
Alright, well this is pretty strange, but if you add `pointerEvents="box-none"` to `Animated.View` then it works on both.
Can you confirm on your side?

**Comment by tongyy** [comment]
it works. the solution looks okay. why did you say this is strange? was it supposed to propagate to Animated.View automatically?
```
 <View pointerEvents="box-none" style={positionCss}>
      {debug && getDebugView()}
      <Animated.View
        pointerEvents="box-none"
```

**Comment by baconcheese113** [comment]
It's strange because the Animated.View always starts rendered at the top of the screen for each draggable even though it's getting the x/y position from the child.

But yea, if you're cool with it I think v3 is ready. I collaborated in this repo because of another project I was working on so I'll be able to do more testing from there, but I expect any changes I add would be patch or minor changes....not renaming all the props 😄

**Comment by tongyy** [comment]
well done! it's so great to have you as a collaborator. since I don't work any mobile project anymore, it's hard to maintain on my own. luckily, you showed up.  I believe you are going to make it great again:) 
You can merge it. I will run master code and test it again before I publish it to NPM.

**Comment by baconcheese113** [comment]
Oh still not seeing myself as a collaborator in npm

**Comment by tongyy** [comment]
because that is Version 2.0.0. when I publish Version 3.0.0, you will see it.

**Comment by baconcheese113** [comment]
I see the Admin panel and that i'm a Maintainer, just not a collaborator in the publicly visible side panel

**Comment by baconcheese113** [comment]
I see it now, thanks!

**Pull request merged**
